use crate::config::{self, Config, Loaded, Store};
use crate::error::StitchError;
use crate::hooks::{self, HookEnv};
use crate::linker::{self, LinkStatus};
use crate::plan::{LinkRequires, Plan, PlanOp, PlanStore, TargetState, path_to_string};
use crate::platform::Platform;
use crate::render;
use globset::{GlobBuilder, GlobSet, GlobSetBuilder};
use serde::Serialize;
use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

#[derive(Debug)]
pub enum ApplyAction {
    Created(PathBuf),
    /// The old target was replaced by a link to `source`. `old_resolves_to`
    /// is `Some` for a broken repo-owned symlink, `None` for a real file/dir.
    Replaced {
        target: PathBuf,
        old_resolves_to: Option<PathBuf>,
    },
    /// The conflicting real file/dir was renamed to `{target}.bak` and the
    /// link created (`apply --force`). `target` is now symlinked; `backup`
    /// holds the original content.
    BackedUp {
        target: PathBuf,
        backup: PathBuf,
    },
    /// A path is occupied by something other than the desired source.
    /// `resolves_to` is `None` for a real file/dir, `Some` for a symlink that
    /// points elsewhere (foreign or another store).
    Conflict {
        target: PathBuf,
        resolves_to: Option<PathBuf>,
    },
    SkippedPlatform,
    AlreadyLinked(PathBuf),
    /// Templated entry: staged content was (or would be) refreshed; the link
    /// already pointed at the staging path. Surfaced so `diff`/`apply` can
    /// answer "would apply change anything?" for content, not only link state.
    ContentChanged(PathBuf),
    /// A stale stitch-owned file-mode link was removed (or would be removed in
    /// a dry run) because its source is no longer in the resolved entry set.
    Removed(PathBuf),
    Error(StitchError),
}

/// Convenience: wrap a plain-string apply error as an internal failure.
fn internal_error(message: impl Into<String>) -> ApplyAction {
    ApplyAction::Error(StitchError::internal(message))
}

#[derive(Debug)]
pub struct ApplyResult {
    pub store_name: String,
    pub actions: Vec<ApplyAction>,
}

/// Flags controlling how `apply` reconciles each link.
#[derive(Debug, Clone, Copy)]
pub struct ApplyOpts {
    pub dry_run: bool,
    /// Rename real-file/dir conflicts to `{target}.bak` and link instead of
    /// stopping. Foreign symlinks remain hard conflicts regardless.
    pub force: bool,
}

/// Apply all stores in the config. Returns the executed (or previewed) plan
/// and any warnings generated by side-effecting steps such as post-hooks.
pub fn apply_all(
    repo_root: &Path,
    config: &Config,
    platform: &Platform,
    opts: ApplyOpts,
) -> (Plan, Vec<String>) {
    let mut warnings = Vec::new();
    let sorted: BTreeMap<_, _> = config.stores.iter().collect();
    let results: Vec<_> = sorted
        .into_iter()
        .map(|(name, store)| {
            apply_store(
                repo_root,
                name,
                store,
                platform,
                &config.vars,
                opts,
                &mut warnings,
            )
        })
        .collect();
    (to_plan(repo_root, config, &results, opts), warnings)
}

/// Pure classification: what would `apply` do? No hooks, no staging writes, no
/// link mutations. This is the `Plan` that `diff` and `apply --json` render.
pub fn compute_plan(
    repo_root: &Path,
    config: &Config,
    platform: &Platform,
    opts: ApplyOpts,
) -> Plan {
    // Force dry-run so no side effects run, but preserve the force flag for
    // conflict classification (backed up vs conflict).
    let classify_opts = ApplyOpts {
        dry_run: true,
        force: opts.force,
    };
    apply_all(repo_root, config, platform, classify_opts).0
}

/// Whether an apply on this platform could render an on-disk template source.
/// Used to make the `.gitignore` trust boundary conditional for upgraded repos:
/// plain stores need no migration, but rendering refuses to create output until
/// staging is ignored.
pub fn has_active_template_sources(repo_root: &Path, config: &Config, platform: &Platform) -> bool {
    config.stores.iter().any(|(name, store)| {
        if !platform.matches_when(&store.when) {
            return false;
        }
        let store_dir = repo_root.join(name);
        if store.is_multi_target() {
            store.targets.values().any(|target| {
                platform.matches_when(&target.when)
                    && target_has_template_source(
                        &store_dir,
                        &target.files,
                        &target.patterns,
                        &target.ignore,
                    )
            })
        } else {
            target_has_template_source(&store_dir, &store.files, &store.patterns, &store.ignore)
        }
    })
}

fn target_has_template_source(
    store_dir: &Path,
    files: &[String],
    patterns: &[String],
    ignore: &[String],
) -> bool {
    let LinkTargets::Files(names) = resolve_target_names(store_dir, files, patterns, ignore) else {
        return false;
    };
    names.into_iter().any(|source_name| {
        let entry = render::resolve_entry(&source_name);
        entry.is_template && store_dir.join(entry.source_rel).is_file()
    })
}

/// Apply a single store.
pub fn apply_store(
    repo_root: &Path,
    name: &str,
    store: &Store,
    platform: &Platform,
    vars: &BTreeMap<String, String>,
    opts: ApplyOpts,
    warnings: &mut Vec<String>,
) -> ApplyResult {
    if !platform.matches_when(&store.when) {
        return ApplyResult {
            store_name: name.to_string(),
            actions: vec![ApplyAction::SkippedPlatform],
        };
    }

    let store_dir = repo_root.join(name);
    if !store_dir.exists() {
        return ApplyResult {
            store_name: name.to_string(),
            actions: vec![internal_error(format!(
                "store directory '{}' does not exist",
                name
            ))],
        };
    }

    let mut actions = Vec::new();

    // Per-store pre-hook: aborts the store on failure (SPEC). Skipped under
    // dry-run — running a shell command is a side effect, not a preview.
    if !opts.dry_run
        && let Some(pre) = &store.hooks.pre
    {
        let env = HookEnv {
            root: repo_root,
            store: Some(name),
            target: store.target.as_deref(),
            action: "apply",
        };
        if let Err(msg) = hooks::run_store_hook(pre, &env, platform) {
            actions.push(ApplyAction::Error(StitchError::hook("pre", msg)));
            return ApplyResult {
                store_name: name.to_string(),
                actions,
            };
        }
    }

    // Reconciliation is derived from desired sources, not successful entry
    // application. A render/resolution failure and a target skipped by `when`
    // must preserve a live staged render and its owned link; otherwise a
    // harmless config mistake turns a working link dangling.
    let mut keep_links: BTreeSet<String> = BTreeSet::new();
    // File-mode cleanup is target-specific. A store can have multiple targets,
    // and two target entries may even share a target path, so union their
    // configured link names before scanning that path.
    let mut target_keep_links: BTreeMap<PathBuf, BTreeSet<String>> = BTreeMap::new();

    let empty_link_rels = BTreeSet::new();
    if store.is_multi_target() {
        // Build every desired keep-set before applying any target. An active
        // whole-dir target must see a skipped file-mode sibling that shares its
        // path; otherwise it could erase that sibling before its turn.
        for target_entry in store.targets.values() {
            collect_reconciliation_keeps(
                &store_dir,
                &config::expand_home(&target_entry.target),
                &target_entry.files,
                &target_entry.patterns,
                &target_entry.ignore,
                &mut keep_links,
                &mut target_keep_links,
            );
        }
        for target_entry in store.targets.values() {
            if !platform.matches_when(&target_entry.when) {
                continue;
            }
            let target_path = config::expand_home(&target_entry.target);
            let target_link_rels = target_keep_links
                .get(&target_path)
                .unwrap_or(&empty_link_rels);
            actions.extend(apply_target(
                name,
                &store_dir,
                &target_path,
                repo_root,
                &target_entry.files,
                &target_entry.patterns,
                &target_entry.ignore,
                target_link_rels,
                platform,
                vars,
                opts,
            ));
        }
    } else if let Some(ref target_str) = store.target {
        let target_path = config::expand_home(target_str);
        collect_reconciliation_keeps(
            &store_dir,
            &target_path,
            &store.files,
            &store.patterns,
            &store.ignore,
            &mut keep_links,
            &mut target_keep_links,
        );
        let target_link_rels = target_keep_links
            .get(&target_path)
            .unwrap_or(&empty_link_rels);
        actions.extend(apply_target(
            name,
            &store_dir,
            &target_path,
            repo_root,
            &store.files,
            &store.patterns,
            &store.ignore,
            target_link_rels,
            platform,
            vars,
            opts,
        ));
    } else {
        actions.push(internal_error("no target configured"));
    }

    // Reconcile file-mode links before staging: a deleted source must not leave
    // a target symlink pointing at a render that is about to disappear. The
    // helper is dry-run aware so `diff` previews removals without mutating.
    let mut link_reconciliation_failed = false;
    for (target_path, link_rels) in target_keep_links {
        match render::reconcile_store_links(
            &target_path,
            repo_root,
            &store_dir,
            name,
            &link_rels,
            opts.dry_run,
        ) {
            Ok(removed) => actions.extend(removed.into_iter().map(ApplyAction::Removed)),
            Err(e) => {
                link_reconciliation_failed = true;
                actions.push(internal_error(e));
            }
        }
    }

    // Reap staging only after target cleanup fully succeeds. An I/O failure
    // while unlinking a stale target must leave its render readable rather
    // than converting the failure into a dangling link.
    if !opts.dry_run
        && !link_reconciliation_failed
        && let Err(e) = render::reconcile_store_staging(repo_root, name, &keep_links)
    {
        actions.push(internal_error(e));
    }

    // Per-store post-hook: warns on failure — the store is already applied,
    // so post-hook failure does not abort (SPEC). Skipped under dry-run.
    if !opts.dry_run
        && let Some(post) = &store.hooks.post
    {
        let env = HookEnv {
            root: repo_root,
            store: Some(name),
            target: store.target.as_deref(),
            action: "apply",
        };
        if let Err(msg) = hooks::run_store_hook(post, &env, platform) {
            warnings.push(format!("store '{name}' post-hook: {msg}"));
        }
    }

    ApplyResult {
        store_name: name.to_string(),
        actions,
    }
}

#[allow(clippy::too_many_arguments)] // thin dispatcher over resolve + per-entry apply
fn apply_target(
    store_name: &str,
    store_dir: &Path,
    target_path: &Path,
    repo_root: &Path,
    files: &[String],
    patterns: &[String],
    ignore: &[String],
    target_link_rels: &BTreeSet<String>,
    platform: &Platform,
    vars: &BTreeMap<String, String>,
    opts: ApplyOpts,
) -> Vec<ApplyAction> {
    match resolve_targets(store_dir, files, patterns, ignore) {
        Err(msg) => vec![ApplyAction::Error(StitchError::path_validation(msg))],
        Ok(LinkTargets::WholeDir) => apply_whole_dir(
            store_name,
            store_dir,
            target_path,
            repo_root,
            target_link_rels,
            opts,
        ),
        Ok(LinkTargets::Files(names)) => {
            let (replaces_whole_dir, mut actions) = match prepare_file_mode_target(
                store_name,
                store_dir,
                target_path,
                repo_root,
                &names,
                platform,
                vars,
                opts,
            ) {
                Ok(prepared) => prepared,
                Err(action) => return vec![action],
            };
            for source_name in &names {
                if replaces_whole_dir && opts.dry_run {
                    actions.push(preview_file_entry_after_root_removal(
                        target_path,
                        source_name,
                    ));
                } else {
                    actions.push(apply_file_entry(
                        store_name,
                        store_dir,
                        target_path,
                        repo_root,
                        source_name,
                        platform,
                        vars,
                        opts,
                    ));
                }
            }
            actions
        }
    }
}

/// Remove a verified whole-directory link before creating file-mode children.
/// Without this ordering, POSIX follows the root symlink and writes new child
/// links into the store itself.
#[allow(clippy::too_many_arguments)]
fn prepare_file_mode_target(
    store_name: &str,
    store_dir: &Path,
    target_path: &Path,
    repo_root: &Path,
    source_names: &[String],
    platform: &Platform,
    vars: &BTreeMap<String, String>,
    opts: ApplyOpts,
) -> Result<(bool, Vec<ApplyAction>), ApplyAction> {
    let metadata = match std::fs::symlink_metadata(target_path) {
        Ok(metadata) => metadata,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok((false, Vec::new())),
        Err(e) => {
            return Err(internal_error(format!(
                "could not inspect {}: {e}",
                target_path.display()
            )));
        }
    };
    if !metadata.file_type().is_symlink() {
        return Ok((false, Vec::new()));
    }

    // Only this store's exact whole-dir link may be promoted. A foreign link,
    // or a link to another store in the same repo, remains a conflict.
    match linker::check_link(target_path, store_dir) {
        LinkStatus::Linked => {}
        LinkStatus::Broken(resolved) => {
            return Err(ApplyAction::Conflict {
                target: target_path.to_path_buf(),
                resolves_to: Some(resolved),
            });
        }
        _ => {
            return Err(ApplyAction::Conflict {
                target: target_path.to_path_buf(),
                resolves_to: None,
            });
        }
    }
    preflight_file_mode_promotion(
        store_name,
        store_dir,
        repo_root,
        source_names,
        platform,
        vars,
        opts,
    )?;
    if opts.dry_run {
        return Ok((true, vec![ApplyAction::Removed(target_path.to_path_buf())]));
    }

    match linker::remove_link_to(target_path, store_dir, repo_root) {
        Ok(true) => Ok((true, vec![ApplyAction::Removed(target_path.to_path_buf())])),
        // The link was repointed between check and removal. Do not risk
        // writing through it; report the now-unmanaged root as a conflict.
        Ok(false) => Err(ApplyAction::Conflict {
            target: target_path.to_path_buf(),
            resolves_to: std::fs::read_link(target_path).ok(),
        }),
        Err(e) => Err(internal_error(format!(
            "could not remove whole-directory link {}: {e}",
            target_path.display()
        ))),
    }
}

/// Verify a whole-directory → file-mode promotion before unlinking its live
/// root. Templates are rendered/staged first; a bad template or missing source
/// leaves the old directory link intact.
#[allow(clippy::too_many_arguments)]
fn preflight_file_mode_promotion(
    store_name: &str,
    store_dir: &Path,
    repo_root: &Path,
    source_names: &[String],
    platform: &Platform,
    vars: &BTreeMap<String, String>,
    opts: ApplyOpts,
) -> Result<(), ApplyAction> {
    let entries: Vec<_> = source_names
        .iter()
        .map(|name| render::resolve_entry(name))
        .collect();
    for entry in &entries {
        let source_path = store_dir.join(&entry.source_rel);
        if !source_path.exists() {
            return Err(internal_error(format!(
                "source does not exist: {}",
                source_path.display()
            )));
        }
    }
    for entry in entries.iter().filter(|entry| entry.is_template) {
        let source_path = store_dir.join(&entry.source_rel);
        let result = if opts.dry_run {
            render::staged_differs(
                repo_root,
                store_name,
                &entry.source_rel,
                &source_path,
                platform,
                vars,
            )
            .map(|_| ())
        } else {
            render::stage_template(
                repo_root,
                store_name,
                &entry.source_rel,
                &source_path,
                platform,
                vars,
            )
            .map(|_| ())
        };
        if let Err(e) = result {
            return Err(ApplyAction::Error(StitchError::render(&source_path, e)));
        }
    }
    Ok(())
}

/// Preview an entry after [`prepare_file_mode_target`] would remove the old
/// whole-directory root. The promotion preflight already verified its source
/// and template render, so every child link is known to be absent afterwards.
fn preview_file_entry_after_root_removal(target_path: &Path, source_name: &str) -> ApplyAction {
    let entry = render::resolve_entry(source_name);
    ApplyAction::Created(target_path.join(entry.link_rel))
}

/// Apply a whole-directory store, including a safe transition back from file mode.
///
/// A store with templates is promoted to a real target directory containing
/// individual links. If its last template disappears, its desired state becomes
/// a single directory link again. The real target dir is normally a conflict,
/// but we can prove it came from file mode when it contains stale links owned by
/// this store. Remove only those links, then replace the directory only when it
/// is empty. Foreign content keeps the ordinary conflict behavior.
fn apply_whole_dir(
    store_name: &str,
    store_dir: &Path,
    target_path: &Path,
    repo_root: &Path,
    keep_link_rels: &BTreeSet<String>,
    opts: ApplyOpts,
) -> Vec<ApplyAction> {
    // Do not scan a correct directory symlink: `Path::is_dir` follows it, and
    // treating the root link as a stale child would remove the desired state.
    if target_path.is_symlink() || !target_path.is_dir() {
        return vec![apply_single_link(store_dir, target_path, repo_root, opts)];
    }

    let removed = match render::reconcile_store_links(
        target_path,
        repo_root,
        store_dir,
        store_name,
        keep_link_rels,
        opts.dry_run,
    ) {
        Ok(removed) => removed,
        Err(e) => return vec![internal_error(e)],
    };
    let had_stale_links = !removed.is_empty();
    let mut actions: Vec<ApplyAction> = removed.into_iter().map(ApplyAction::Removed).collect();

    // An empty pre-existing directory is still a user-owned conflict. Only
    // replace it automatically after proving that we removed stale links for
    // this exact store from it.
    if !had_stale_links {
        actions.push(apply_single_link(store_dir, target_path, repo_root, opts));
        return actions;
    }

    let empty = if opts.dry_run {
        target_would_be_empty_after_removals(target_path, &actions)
    } else {
        remove_empty_target_dir(target_path)
    };
    match empty {
        Ok(true) => {
            if opts.dry_run {
                actions.push(ApplyAction::Replaced {
                    target: target_path.to_path_buf(),
                    old_resolves_to: None,
                });
            } else {
                match linker::create_link(target_path, store_dir) {
                    Ok(()) => actions.push(ApplyAction::Replaced {
                        target: target_path.to_path_buf(),
                        old_resolves_to: None,
                    }),
                    Err(e) => actions.push(internal_error(e.to_string())),
                }
            }
        }
        Ok(false) => actions.push(apply_single_link(store_dir, target_path, repo_root, opts)),
        Err(e) => actions.push(internal_error(e)),
    }
    actions
}

/// Whether `target_path` would become an empty directory after the removals
/// reported by a dry-run stale-link reconciliation.
fn target_would_be_empty_after_removals(
    target_path: &Path,
    actions: &[ApplyAction],
) -> Result<bool, String> {
    let removed: BTreeSet<&Path> = actions
        .iter()
        .filter_map(|action| match action {
            ApplyAction::Removed(path) => Some(path.as_path()),
            _ => None,
        })
        .collect();

    for entry in walkdir::WalkDir::new(target_path)
        .follow_links(false)
        .into_iter()
    {
        let entry = entry.map_err(|e| {
            format!(
                "could not scan target {} while previewing directory replacement: {e}",
                target_path.display()
            )
        })?;
        if entry.depth() == 0 {
            continue;
        }
        if entry.file_type().is_symlink() && removed.contains(entry.path()) {
            continue;
        }
        // Do not erase even an empty nested directory: it could have been
        // created by the user after the prior file-mode apply. The target root
        // itself is replaced only when it becomes directly empty.
        return Ok(false);
    }
    Ok(true)
}

/// Remove the target root only when it is directly empty. Nested directories
/// are deliberately retained: without a state database we cannot distinguish a
/// directory created for a prior file-mode link from an empty one a user made.
fn remove_empty_target_dir(target_path: &Path) -> Result<bool, String> {
    match std::fs::remove_dir(target_path) {
        Ok(()) => Ok(true),
        Err(e) if e.kind() == std::io::ErrorKind::DirectoryNotEmpty => Ok(false),
        Err(e) => Err(format!(
            "could not remove empty target directory {}: {e}",
            target_path.display()
        )),
    }
}

/// Apply one resolved file-mode entry. Templates render to staging first;
/// non-templates link the store source directly.
#[allow(clippy::too_many_arguments)] // mirrors apply_target's parameter set
fn apply_file_entry(
    store_name: &str,
    store_dir: &Path,
    target_path: &Path,
    repo_root: &Path,
    source_name: &str,
    platform: &Platform,
    vars: &BTreeMap<String, String>,
    opts: ApplyOpts,
) -> ApplyAction {
    let entry = render::resolve_entry(source_name);
    let source_path = store_dir.join(&entry.source_rel);
    let target = target_path.join(&entry.link_rel);

    if !entry.is_template {
        return apply_single_link(&source_path, &target, repo_root, opts);
    }

    let staged = render::staging_path(repo_root, store_name, &entry.link_rel);

    if opts.dry_run {
        // Content dimension: fresh in-memory render vs staged. Never write.
        let content_differs = match render::staged_differs(
            repo_root,
            store_name,
            &entry.source_rel,
            &source_path,
            platform,
            vars,
        ) {
            Ok(d) => d,
            Err(e) => return ApplyAction::Error(StitchError::render(&source_path, e)),
        };
        let link_action = apply_single_link(&staged, &target, repo_root, opts);
        if content_differs && matches!(link_action, ApplyAction::AlreadyLinked(_)) {
            ApplyAction::ContentChanged(target)
        } else {
            link_action
        }
    } else {
        // Render-before-link: failure skips the link entirely (no broken link).
        let (link_source, wrote) = match render::stage_template(
            repo_root,
            store_name,
            &entry.source_rel,
            &source_path,
            platform,
            vars,
        ) {
            Ok(render::StageOutcome::Written(p)) => (p, true),
            Ok(render::StageOutcome::Unchanged(p)) => (p, false),
            Err(e) => return ApplyAction::Error(StitchError::render(&source_path, e)),
        };
        let action = apply_single_link(&link_source, &target, repo_root, opts);
        // Link already correct but staging was refreshed → content changed.
        if wrote && matches!(action, ApplyAction::AlreadyLinked(_)) {
            ApplyAction::ContentChanged(target)
        } else {
            action
        }
    }
}

fn apply_single_link(
    source: &Path,
    target: &Path,
    repo_root: &Path,
    opts: ApplyOpts,
) -> ApplyAction {
    let status = linker::check_link(target, source);

    match status {
        LinkStatus::Linked => ApplyAction::AlreadyLinked(target.to_path_buf()),
        LinkStatus::Missing => {
            if opts.dry_run {
                ApplyAction::Created(target.to_path_buf())
            } else {
                match linker::create_link(target, source) {
                    Ok(()) => ApplyAction::Created(target.to_path_buf()),
                    Err(e) => internal_error(e.to_string()),
                }
            }
        }
        // A real file or directory occupies the target. Without --force this
        // is a hard conflict; with --force the target is renamed to `.bak`
        // and the link takes its place. (Foreign symlinks never reach here —
        // they surface as `Broken` below and stay conflicts even under force.)
        LinkStatus::Conflict(_) => {
            if !opts.force {
                ApplyAction::Conflict {
                    target: target.to_path_buf(),
                    resolves_to: None,
                }
            } else {
                force_backup_link(source, target, opts.dry_run)
            }
        }
        LinkStatus::Broken(resolved) => {
            // A symlink that isn't ours. Relink only if it points into this
            // repo (stale stitch state — the store moved or a file was
            // renamed); a foreign symlink (stow/chezmoi/Nix/Home-Manager, or
            // a dangling user link) is a conflict, never silently clobbered —
            // even under --force.
            if !linker::points_into_repo(target, repo_root) {
                return ApplyAction::Conflict {
                    target: target.to_path_buf(),
                    resolves_to: Some(resolved),
                };
            }
            if opts.dry_run {
                return ApplyAction::Replaced {
                    target: target.to_path_buf(),
                    old_resolves_to: Some(resolved),
                };
            }
            let old_resolves_to = resolved.clone();
            if let Err(e) = std::fs::remove_file(target) {
                return internal_error(e.to_string());
            }
            match linker::create_link(target, source) {
                Ok(()) => ApplyAction::Replaced {
                    target: target.to_path_buf(),
                    old_resolves_to: Some(old_resolves_to),
                },
                Err(e) => internal_error(e.to_string()),
            }
        }
    }
}

/// Resolve a real-file/dir conflict (`apply --force`) by renaming the target
/// to `{target}.bak` and creating the symlink.
///
/// Fails — leaving the original target in place — if a backup already exists
/// (never silently destroy a prior backup) or the link step fails after the
/// rename (the backup is restored so the user loses nothing).
fn force_backup_link(source: &Path, target: &Path, dry_run: bool) -> ApplyAction {
    let backup = backup_path(target);

    // Catch anything at the backup path in both dry-run and real modes so the
    // rendered plan is honest and `diff --force` matches real execution.
    if backup.symlink_metadata().is_ok() {
        let resolves_to = std::fs::read_link(&backup).ok();
        return ApplyAction::Conflict {
            target: backup,
            resolves_to,
        };
    }

    if dry_run {
        return ApplyAction::BackedUp {
            target: target.to_path_buf(),
            backup,
        };
    }
    if let Err(e) = std::fs::rename(target, &backup) {
        return internal_error(format!(
            "failed to back up {} → {}: {}",
            target.display(),
            backup.display(),
            e
        ));
    }
    if let Err(e) = linker::create_link(target, source) {
        // Restore the original so the user is left with their file, not a
        // missing target. Best-effort: a (near-impossible) restore failure
        // is ignored rather than masking the original link error.
        let _ = std::fs::rename(&backup, target);
        return internal_error(format!(
            "failed to link after backing up {}: {e}",
            target.display()
        ));
    }
    ApplyAction::BackedUp {
        target: target.to_path_buf(),
        backup,
    }
}

/// Backup path for a target: `{target}.bak`.
///
/// Appends rather than `Path::with_extension("bak")` — dotfiles like `.bashrc`
/// have no extension in `Path` semantics, so `with_extension` would yield just
/// `.bak`, dropping the name. Uses `OsString` to stay correct on non-UTF8 paths.
fn backup_path(target: &Path) -> PathBuf {
    let mut name = target.as_os_str().to_owned();
    name.push(".bak");
    name.into()
}

/// Convert execution results into a `Plan` with source paths and preconditions.
/// This is where the M3 upgrade happens: every `ApplyAction` gets the source
/// and `requires` state it needs for the M4 executor and for JSON/text render.
fn to_plan(repo_root: &Path, config: &Config, results: &[ApplyResult], _opts: ApplyOpts) -> Plan {
    let mut stores = Vec::new();
    for result in results {
        let store = config.stores.get(&result.store_name);
        let store_dir = repo_root.join(&result.store_name);
        let mut ops = Vec::new();
        for action in &result.actions {
            ops.push(action_to_plan_op(
                repo_root,
                &store_dir,
                store,
                &result.store_name,
                action,
            ));
        }
        stores.push(PlanStore {
            store_name: result.store_name.clone(),
            ops,
        });
    }
    Plan::from_stores(stores)
}

fn action_to_plan_op(
    repo_root: &Path,
    store_dir: &Path,
    store: Option<&Store>,
    store_name: &str,
    action: &ApplyAction,
) -> PlanOp {
    match action {
        ApplyAction::SkippedPlatform => PlanOp::SkippedPlatform,
        ApplyAction::Error(e) => PlanOp::Error {
            message: e.to_string(),
            class: e.class().id().to_string(),
        },
        ApplyAction::Conflict {
            target,
            resolves_to,
        } => PlanOp::Conflict {
            target: path_to_string(target),
            resolves_to: resolves_to.as_ref().map(|p| path_to_string(p)),
        },
        ApplyAction::Removed(target) => {
            let target_str = path_to_string(target);
            let source = resolve_remove_source(repo_root, store_dir, store, store_name, target);
            let requires = remove_requires(repo_root, store_dir, store, target, &source);
            PlanOp::RemoveLink {
                target: target_str,
                source,
                requires,
            }
        }
        ApplyAction::AlreadyLinked(target) => {
            let target_str = path_to_string(target);
            let source = resolve_link_source(repo_root, store_dir, store, store_name, target)
                .unwrap_or_else(|| target_str.clone());
            PlanOp::AlreadyLinked {
                target: target_str,
                source: source.clone(),
                requires: LinkRequires::new(TargetState::SymlinkTo(source)),
            }
        }
        ApplyAction::Created(target) => {
            let target_str = path_to_string(target);
            let source = resolve_link_source(repo_root, store_dir, store, store_name, target)
                .unwrap_or_else(|| target_str.clone());
            PlanOp::CreateLink {
                target: target_str,
                source,
                requires: LinkRequires::new(TargetState::Absent),
            }
        }
        ApplyAction::Replaced {
            target,
            old_resolves_to,
        } => {
            let target_str = path_to_string(target);
            let source = resolve_link_source(repo_root, store_dir, store, store_name, target)
                .unwrap_or_else(|| target_str.clone());
            let requires_target = match old_resolves_to {
                Some(old) => TargetState::SymlinkTo(path_to_string(old)),
                None => TargetState::RealFile,
            };
            PlanOp::ReplaceLink {
                target: target_str,
                source,
                old_resolves_to: old_resolves_to.as_ref().map(|p| path_to_string(p)),
                requires: LinkRequires::new(requires_target),
            }
        }
        ApplyAction::ContentChanged(target) => {
            let target_str = path_to_string(target);
            let source = resolve_link_source(repo_root, store_dir, store, store_name, target)
                .unwrap_or_else(|| target_str.clone());
            PlanOp::ContentChanged {
                target: target_str,
                source: source.clone(),
                requires: LinkRequires::new(TargetState::SymlinkTo(source)),
            }
        }
        ApplyAction::BackedUp { target, backup } => {
            let target_str = path_to_string(target);
            let backup_str = path_to_string(backup);
            let source = resolve_link_source(repo_root, store_dir, store, store_name, target)
                .unwrap_or_else(|| target_str.clone());
            PlanOp::BackupAndLink {
                target: target_str,
                source,
                backup: backup_str,
                requires: LinkRequires::with_backup(TargetState::RealFile, TargetState::Absent),
            }
        }
    }
}

fn resolve_remove_source(
    repo_root: &Path,
    store_dir: &Path,
    store: Option<&Store>,
    store_name: &str,
    target: &Path,
) -> Option<String> {
    if !target.is_symlink() {
        return None;
    }
    let resolved = std::fs::read_link(target).ok()?;
    if !linker::points_into_repo(target, repo_root) {
        return None;
    }
    // Whole-directory root removal: the link points exactly at the store dir.
    if let Ok(rel) = store_dir.canonicalize()
        && resolved == rel
    {
        return Some(path_to_string(store_dir));
    }
    // File-mode stale link: resolve back to the store-relative source.
    resolve_link_source(repo_root, store_dir, store, store_name, target)
}

fn remove_requires(
    repo_root: &Path,
    store_dir: &Path,
    _store: Option<&Store>,
    target: &Path,
    source: &Option<String>,
) -> LinkRequires {
    if let Some(src) = source
        && let Ok(resolved) = std::fs::read_link(target)
        && (resolved == store_dir || resolved == Path::new(src))
    {
        return LinkRequires::new(TargetState::SymlinkTo(src.clone()));
    }
    if target.is_symlink()
        && linker::points_into_repo(target, repo_root)
        && let Ok(resolved) = std::fs::read_link(target)
    {
        return LinkRequires::new(TargetState::SymlinkTo(path_to_string(&resolved)));
    }
    LinkRequires::new(TargetState::SymlinkIntoRepo)
}

fn resolve_link_source(
    repo_root: &Path,
    store_dir: &Path,
    store: Option<&Store>,
    store_name: &str,
    target: &Path,
) -> Option<String> {
    // Whole-directory link: target is the store target itself.
    let store_config = store?;
    for target_path in target_paths_for_store(store_config) {
        if target == target_path {
            return Some(path_to_string(store_dir));
        }
        if let Ok(rel) = target.strip_prefix(&target_path) {
            let link_rel = rel.to_string_lossy().into_owned();
            let names = resolve_target_names(
                store_dir,
                &store_config.files,
                &store_config.patterns,
                &store_config.ignore,
            );
            if let LinkTargets::Files(source_names) = names {
                for source_name in source_names {
                    let entry = render::resolve_entry(&source_name);
                    if entry.link_rel == link_rel {
                        if entry.is_template {
                            return Some(path_to_string(&render::staging_path(
                                repo_root, store_name, &link_rel,
                            )));
                        }
                        return Some(path_to_string(&store_dir.join(&entry.source_rel)));
                    }
                }
            }
        }
    }
    None
}

fn target_paths_for_store(store: &Store) -> Vec<PathBuf> {
    let mut paths = Vec::new();
    if let Some(ref target_str) = store.target {
        paths.push(config::expand_home(target_str));
    }
    for target_entry in store.targets.values() {
        paths.push(config::expand_home(&target_entry.target));
    }
    paths
}

#[derive(Debug)]
pub struct StatusEntry {
    pub store_name: String,
    /// Multi-target name, if this entry belongs to a named target. Single-
    /// target stores have `None`.
    pub target_name: Option<String>,
    /// Repo source path (the `.tmpl` for templates, plain file otherwise).
    /// Never the staged render — status compares the *link* against the
    /// effective source (staging for templates).
    pub source: PathBuf,
    pub target: PathBuf,
    pub status: LinkStatus,
    pub skipped_platform: bool,
    /// True when this entry is backed by a `.tmpl` (link points at staging).
    pub is_template: bool,
}

/// Get status for all stores.
pub fn status_all(repo_root: &Path, config: &Config, platform: &Platform) -> Vec<StatusEntry> {
    let mut entries = Vec::new();
    let sorted: BTreeMap<_, _> = config.stores.iter().collect();

    for (name, store) in sorted {
        if !platform.matches_when(&store.when) {
            entries.push(StatusEntry {
                store_name: name.clone(),
                target_name: None,
                source: PathBuf::new(),
                target: PathBuf::new(),
                status: LinkStatus::Missing,
                skipped_platform: true,
                is_template: false,
            });
            continue;
        }

        let store_dir = repo_root.join(name);
        if store.is_multi_target() {
            for (target_name, target_entry) in &store.targets {
                if !platform.matches_when(&target_entry.when) {
                    continue;
                }
                let target_path = config::expand_home(&target_entry.target);
                entries.extend(collect_statuses(
                    repo_root,
                    name,
                    Some(target_name),
                    &store_dir,
                    &target_path,
                    &target_entry.files,
                    &target_entry.patterns,
                    &target_entry.ignore,
                ));
            }
        } else if let Some(ref target_str) = store.target {
            let target_path = config::expand_home(target_str);
            entries.extend(collect_statuses(
                repo_root,
                name,
                None,
                &store_dir,
                &target_path,
                &store.files,
                &store.patterns,
                &store.ignore,
            ));
        }
    }

    entries
}

#[allow(clippy::too_many_arguments)] // internal helper; arity matches the data it carries
fn collect_statuses(
    repo_root: &Path,
    name: &str,
    target_name: Option<&str>,
    store_dir: &Path,
    target_path: &Path,
    files: &[String],
    patterns: &[String],
    ignore: &[String],
) -> Vec<StatusEntry> {
    let mut entries = Vec::new();
    match resolve_targets(store_dir, files, patterns, ignore) {
        Err(_) => {
            // Collision / resolution error: surface nothing here; apply will
            // report the Error action. Status stays quiet on bad config.
        }
        Ok(LinkTargets::WholeDir) => {
            entries.push(StatusEntry {
                store_name: name.to_string(),
                target_name: target_name.map(str::to_owned),
                source: store_dir.to_path_buf(),
                target: target_path.to_path_buf(),
                status: linker::check_link(target_path, store_dir),
                skipped_platform: false,
                is_template: false,
            });
        }
        Ok(LinkTargets::Files(names)) => {
            for source_name in &names {
                let entry = render::resolve_entry(source_name);
                let repo_source = store_dir.join(&entry.source_rel);
                let target = target_path.join(&entry.link_rel);
                // Link source is staging for templates, repo file otherwise.
                let link_source = if entry.is_template {
                    render::staging_path(repo_root, name, &entry.link_rel)
                } else {
                    repo_source.clone()
                };
                entries.push(StatusEntry {
                    store_name: name.to_string(),
                    target_name: target_name.map(str::to_owned),
                    source: repo_source,
                    target: target.clone(),
                    status: linker::check_link(&target, &link_source),
                    skipped_platform: false,
                    is_template: entry.is_template,
                });
            }
        }
    }
    entries
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "lowercase")]
pub enum Severity {
    Error,
    Warning,
    Info,
}

/// A single health-check finding from `stitch doctor`.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct DoctorFinding {
    pub id: &'static str,
    pub severity: Severity,
    pub message: String,
    pub path: Option<PathBuf>,
    pub hint: Option<String>,
}

#[derive(Debug)]
pub struct DoctorResult {
    pub findings: Vec<DoctorFinding>,
}

/// Run health checks.
///
/// Takes [`Loaded`] (both halves) rather than just the merged [`Config`] so it
/// can detect orphaned behavior: a store present in `stitch.toml` (authored)
/// but missing from `state.toml` (generated) — e.g. left behind deliberately
/// by `remove`, which never rewrites the authored file.
pub fn doctor(repo_root: &Path, loaded: &Loaded, platform: &Platform) -> DoctorResult {
    let mut findings = Vec::new();
    let config = &loaded.config;

    // Existing pre-template repos do not need a migration merely because
    // `init` now creates a render directory. Once a configured template or
    // staged output exists, though, this is a hard trust boundary.
    let rendering_in_use = has_active_template_sources(repo_root, config, platform)
        || render::has_staged_output(repo_root);
    if rendering_in_use && !render::repo_gitignore_covers_render(repo_root) {
        findings.push(DoctorFinding {
            id: "missing-render-gitignore",
            severity: Severity::Error,
            message: format!(
                "repo .gitignore is missing `{}` — add that entry before rendering templates; \
                 staged output must never be committed",
                render::RENDER_GITIGNORE_ENTRY
            ),
            path: None,
            hint: Some(format!(
                "add `{}` to the repo's .gitignore",
                render::RENDER_GITIGNORE_ENTRY
            )),
        });
    }

    // Permission contract on an existing staging tree.
    let render_root = render::render_root(repo_root);
    if render_root.exists() {
        match render::path_mode(&render_root) {
            Some(mode) if mode != 0o700 => {
                findings.push(DoctorFinding {
                    id: "staging-permission-drift",
                    severity: Severity::Error,
                    message: format!(
                        "{} has mode {:04o}, expected 0700",
                        render_root.display(),
                        mode
                    ),
                    path: Some(render_root.clone()),
                    hint: Some(format!("chmod 0700 {}", render_root.display())),
                });
            }
            _ => {}
        }
    }

    if config.stores.is_empty() {
        findings.push(DoctorFinding {
            id: "empty-config",
            severity: Severity::Warning,
            message: "no stores configured".into(),
            path: None,
            hint: Some("use `stitch add <path>` to create a store".into()),
        });
        return DoctorResult { findings };
    }

    findings.push(DoctorFinding {
        id: "store-count",
        severity: Severity::Info,
        message: format!("{} stores configured", config.stores.len()),
        path: None,
        hint: None,
    });

    // Orphaned behavior: a store declared in stitch.toml with no state.toml
    // inventory. load-OK (it contributes no link), but worth surfacing so the
    // user can prune the authored entry if it's stale.
    for name in loaded.authored.stores.keys() {
        if !loaded.generated.stores.contains_key(name) {
            findings.push(DoctorFinding {
                id: "orphaned-behavior",
                severity: Severity::Warning,
                message: format!(
                    "store '{name}': behavior configured but no links (orphaned after remove?)"
                ),
                path: None,
                hint: Some(format!(
                    "remove the `{name}` entry from stitch.toml if it is stale"
                )),
            });
        }
    }

    let mut seen_targets: BTreeMap<PathBuf, String> = BTreeMap::new();

    // Compute status once, not per store.
    let all_statuses = status_all(repo_root, config, platform);

    for (name, store) in &config.stores {
        let store_dir = repo_root.join(name);

        if !store_dir.exists() {
            findings.push(DoctorFinding {
                id: "missing-store-dir",
                severity: Severity::Error,
                message: format!(
                    "store '{}': directory '{}' does not exist",
                    name,
                    store_dir.display()
                ),
                path: Some(store_dir),
                hint: Some("create the store directory or remove the store from config".into()),
            });
            continue;
        }

        if store_dir
            .read_dir()
            .map_or(true, |mut d| d.next().is_none())
        {
            findings.push(DoctorFinding {
                id: "empty-store",
                severity: Severity::Warning,
                message: format!("store '{}': directory is empty", name),
                path: Some(store_dir.clone()),
                hint: Some("add files or remove the store".into()),
            });
        }

        if !platform.matches_when(&store.when) {
            findings.push(DoctorFinding {
                id: "platform-skipped",
                severity: Severity::Info,
                message: format!("store '{}': skipped (platform filter)", name),
                path: None,
                hint: None,
            });
            continue;
        }

        if let Some(ref target_str) = store.target {
            let target_path = config::expand_home(target_str);
            if let Some(other) = seen_targets.get(&target_path) {
                findings.push(DoctorFinding {
                    id: "duplicate-target",
                    severity: Severity::Error,
                    message: format!(
                        "stores '{}' and '{}' both target '{}'",
                        name,
                        other,
                        target_path.display()
                    ),
                    path: Some(target_path),
                    hint: Some("reconfigure one store to a different target".into()),
                });
            } else {
                seen_targets.insert(target_path, name.clone());
            }
        }

        for entry in all_statuses
            .iter()
            .filter(|e| e.store_name == *name && !e.skipped_platform)
        {
            if let LinkStatus::Broken(ref resolved) = entry.status {
                findings.push(DoctorFinding {
                    id: "broken-link",
                    severity: Severity::Error,
                    message: format!(
                        "store '{}': broken symlink at {} -> {}",
                        name,
                        entry.target.display(),
                        resolved.display()
                    ),
                    path: Some(entry.target.clone()),
                    hint: Some(format!(
                        "remove or repoint the symlink at {}",
                        entry.target.display()
                    )),
                });
            }

            // Staging drift: tool-owned render differs from a fresh render.
            // Hand-edits (or a vars/env change since last apply) surface here
            // so the next apply's overwrite is never silent.
            if entry.is_template {
                match render::staged_differs(
                    repo_root,
                    name,
                    // source is the repo path; recover the store-relative name.
                    entry
                        .source
                        .strip_prefix(&store_dir)
                        .map(|p| p.to_string_lossy().into_owned())
                        .unwrap_or_else(|_| {
                            entry
                                .source
                                .file_name()
                                .map(|f| f.to_string_lossy().into_owned())
                                .unwrap_or_default()
                        })
                        .as_str(),
                    &entry.source,
                    platform,
                    &config.vars,
                ) {
                    Ok(true) => {
                        findings.push(DoctorFinding {
                            id: "staging-drift",
                            severity: Severity::Warning,
                            message: format!(
                                "store '{}': staged render for {} is stale (run `stitch apply`)",
                                name,
                                entry.target.display()
                            ),
                            path: Some(entry.target.clone()),
                            hint: Some("run `stitch apply`".into()),
                        });
                    }
                    Ok(false) => {}
                    Err(e) => {
                        // A template that fails to render is an error — same
                        // class as a broken link.
                        findings.push(DoctorFinding {
                            id: "render-error",
                            severity: Severity::Error,
                            message: format!("store '{name}': {e}"),
                            path: Some(entry.source.clone()),
                            hint: Some("set missing env vars or fix the template".into()),
                        });
                    }
                }
            }
        }
    }

    DoctorResult { findings }
}

/// Glob patterns always active for every store, regardless of config. Protects
/// against symlinking repo metadata (`.git`, `.stitch`, `.gitignore`,
/// `.DS_Store`) into a target. Per SPEC "Ignore patterns (v0.2)".
const GLOBAL_IGNORES: &[&str] = &[
    ".stitch",
    ".stitch/**",
    ".git",
    ".git/**",
    ".gitignore",
    ".DS_Store",
];

/// What a single store/target should link: one whole-directory symlink, or a
/// list of individual entries (file mode, or a whole-dir store promoted to
/// file mode because it contains ignored content).
enum LinkTargets {
    WholeDir,
    Files(Vec<String>),
}

/// Merge global ignores (always active) with a store's own `ignore` patterns.
fn merge_ignores(store_ignore: &[String]) -> Vec<String> {
    let mut merged: Vec<String> = GLOBAL_IGNORES.iter().map(|s| (*s).to_string()).collect();
    merged.extend(store_ignore.iter().cloned());
    merged
}

/// Build a [`GlobSet`] from patterns. Invalid patterns are warned about on
/// stderr and skipped — one bad pattern does not disable the rest. Returns
/// `None` if `patterns` is empty or every pattern failed to compile.
fn build_globset(patterns: &[String]) -> Option<GlobSet> {
    if patterns.is_empty() {
        return None;
    }
    let mut builder = GlobSetBuilder::new();
    let mut added = 0;
    for pat in patterns {
        match GlobBuilder::new(pat).literal_separator(false).build() {
            Ok(glob) => {
                builder.add(glob);
                added += 1;
            }
            Err(e) => eprintln!("warning: invalid glob pattern '{}': {}", pat, e),
        }
    }
    if added == 0 {
        return None;
    }
    builder.build().ok()
}

/// Sorted, deduped top-level entry names in `store_dir` (non-recursive).
fn top_level_entries(store_dir: &Path) -> Vec<String> {
    let mut names: BTreeSet<String> = BTreeSet::new();
    if let Ok(entries) = std::fs::read_dir(store_dir) {
        for entry in entries.flatten() {
            if let Some(n) = entry.file_name().to_str() {
                names.insert(n.to_string());
            }
        }
    }
    names.into_iter().collect()
}

/// Populate the link and staging keep-sets from actual desired sources.
///
/// This intentionally bypasses collision validation: both sides of a
/// `foo`/`foo.tmpl` collision must keep their currently live output safe while
/// apply reports the resolution error. It also runs before `when` filtering so
/// a skipped target cannot make a shared target directory or staged render
/// look stale.
fn collect_reconciliation_keeps(
    store_dir: &Path,
    target_path: &Path,
    files: &[String],
    patterns: &[String],
    store_ignore: &[String],
    staging_keep_links: &mut BTreeSet<String>,
    target_keep_links: &mut BTreeMap<PathBuf, BTreeSet<String>>,
) {
    let LinkTargets::Files(names) = resolve_target_names(store_dir, files, patterns, store_ignore)
    else {
        return;
    };

    let target_links = target_keep_links
        .entry(target_path.to_path_buf())
        .or_default();
    for source_name in names {
        let entry = render::resolve_entry(&source_name);
        let source_path = store_dir.join(&entry.source_rel);
        // A vanished configured source is stale by definition and therefore
        // must not retain its old target link/render. Existing templates stay
        // live even when their render or resolution subsequently fails.
        if source_path.exists() {
            target_links.insert(entry.link_rel.clone());
            if entry.is_template {
                staging_keep_links.insert(entry.link_rel);
            }
        }
    }
}

/// Resolve what to link for one store/target, rejecting source names that
/// collapse to the same link name (`foo` + `foo.tmpl`).
fn resolve_targets(
    store_dir: &Path,
    files: &[String],
    patterns: &[String],
    store_ignore: &[String],
) -> Result<LinkTargets, String> {
    let targets = resolve_target_names(store_dir, files, patterns, store_ignore);
    if let LinkTargets::Files(ref names) = targets {
        render::check_name_collisions(names)?;
    }
    Ok(targets)
}

/// Resolve the desired mode and source names without collision validation.
/// Kept separate so reconciliation can conservatively preserve a live template
/// when normal resolution reports an error.
fn resolve_target_names(
    store_dir: &Path,
    files: &[String],
    patterns: &[String],
    store_ignore: &[String],
) -> LinkTargets {
    let ignore = merge_ignores(store_ignore);
    let explicit = !files.is_empty() || !patterns.is_empty();
    let names = if !explicit {
        let has_templates = render::store_has_templates(store_dir);
        let entries = top_level_entries(store_dir);
        let ignore_hit = build_globset(&ignore)
            .map(|g| entries.iter().any(|n| g.is_match(n)))
            .unwrap_or(false);

        if has_templates || ignore_hit {
            // Promote: expand to every non-ignored file (full tree), so nested
            // `.tmpl` files become individual links rather than riding inside a
            // whole-dir symlink as literal `.tmpl` sources.
            let all = resolve_files(store_dir, &[], &["**/*".into(), "*".into()], &ignore);
            // `resolve_files` with patterns only includes matches; `**/*` + `*`
            // covers files at any depth. Filter out directories implicitly
            // (resolve_files is file-only).
            //
            // For ignore-only promotion (no templates) the historical behavior
            // listed top-level entries only. Preserve that when there are no
            // templates so a `.git` in a store still promotes to top-level
            // file links rather than exploding into a recursive file list.
            if has_templates {
                all
            } else if let Some(globset) = build_globset(&ignore) {
                entries
                    .into_iter()
                    .filter(|n| !globset.is_match(n))
                    .collect()
            } else {
                entries
            }
        } else {
            return LinkTargets::WholeDir;
        }
    } else {
        resolve_files(store_dir, files, patterns, &ignore)
    };

    LinkTargets::Files(names)
}

/// Resolve the complete file list for a file-mode store.
///
/// Combines explicit `files` with glob `patterns` matched recursively against
/// the store directory via `walkdir`, then removes anything matched by
/// `ignore` patterns (the caller passes the merged global + per-store set).
/// Returns deduplicated, sorted paths relative to `store_dir`.
///
/// Globs are matched against both the file name and the full relative path,
/// so a bare `*.conf` matches at any depth while `subdir/*.conf` scopes the
/// match. Ignore patterns ending in `/` exclude entire subdirectory trees.
fn resolve_files(
    store_dir: &Path,
    files: &[String],
    patterns: &[String],
    ignore: &[String],
) -> Vec<String> {
    let mut seen: BTreeSet<String> = BTreeSet::new();

    // Explicit files always included (validated elsewhere — safe fragments).
    for f in files {
        seen.insert(f.clone());
    }

    // Walk the store directory recursively.
    let include_glob = build_globset(patterns);
    let ignore_glob = build_globset(ignore);
    let ignore_dirs: Vec<&str> = ignore
        .iter()
        .filter(|p| p.ends_with('/'))
        .map(|s| s.as_str())
        .collect();

    for entry in walkdir::WalkDir::new(store_dir)
        .follow_links(false)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let Ok(rel) = entry.path().strip_prefix(store_dir) else {
            continue;
        };
        let rel_str = rel.to_string_lossy();
        let file_name = entry.file_name().to_string_lossy();

        // Check ignore patterns first — if ignored, skip entirely.
        let ignored = ignore_glob
            .as_ref()
            .is_some_and(|g| g.is_match(rel_str.as_ref()) || g.is_match(file_name.as_ref()))
            || ignore_dirs.iter().any(|d| rel_str.starts_with(d));
        if ignored {
            continue;
        }

        // Include if the pattern matches file name or relative path.
        if include_glob
            .as_ref()
            .is_some_and(|g| g.is_match(rel_str.as_ref()) || g.is_match(file_name.as_ref()))
        {
            seen.insert(rel_str.into_owned());
        }
    }

    seen.into_iter().collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_resolve_files_explicit_only() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(&store_dir).unwrap();

        // Create some files in the store dir.
        std::fs::write(store_dir.join(".bashrc"), "...").unwrap();
        std::fs::write(store_dir.join(".zshrc"), "...").unwrap();
        std::fs::write(store_dir.join(".profile"), "...").unwrap();

        let resolved = resolve_files(&store_dir, &[".bashrc".into()], &[], &[]);
        assert_eq!(resolved, vec![".bashrc"]);
    }

    #[test]
    fn test_resolve_files_patterns() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(&store_dir).unwrap();

        std::fs::write(store_dir.join(".bashrc"), "...").unwrap();
        std::fs::write(store_dir.join(".zshrc"), "...").unwrap();
        std::fs::write(store_dir.join(".profile"), "...").unwrap();
        std::fs::write(store_dir.join("config.toml"), "...").unwrap();

        let resolved = resolve_files(
            &store_dir,
            &[],
            &[".*".into()], // match dotfiles
            &[],
        );
        assert_eq!(resolved, vec![".bashrc", ".profile", ".zshrc"]);
    }

    #[test]
    fn test_resolve_files_patterns_with_ignore() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(&store_dir).unwrap();

        std::fs::write(store_dir.join(".bashrc"), "...").unwrap();
        std::fs::write(store_dir.join(".zshrc"), "...").unwrap();
        std::fs::write(store_dir.join(".profile"), "...").unwrap();

        let resolved = resolve_files(
            &store_dir,
            &[],
            &[".*".into()],
            &[".profile".into()], // ignore .profile
        );
        assert_eq!(resolved, vec![".bashrc", ".zshrc"]);
    }

    #[test]
    fn test_resolve_files_explicit_and_patterns_dedup() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(&store_dir).unwrap();

        std::fs::write(store_dir.join(".bashrc"), "...").unwrap();
        std::fs::write(store_dir.join(".zshrc"), "...").unwrap();

        // .bashrc appears in both explicit files and pattern match — should dedup.
        let resolved = resolve_files(&store_dir, &[".bashrc".into()], &[".*".into()], &[]);
        assert_eq!(resolved, vec![".bashrc", ".zshrc"]);
    }

    #[test]
    fn test_resolve_files_ignore_wildcard() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(&store_dir).unwrap();

        std::fs::write(store_dir.join("app.conf"), "...").unwrap();
        std::fs::write(store_dir.join("app.local.conf"), "...").unwrap();
        std::fs::write(store_dir.join("app.prod.conf"), "...").unwrap();

        let resolved = resolve_files(
            &store_dir,
            &[],
            &["*.conf".into()],
            &["*.local.conf".into()],
        );
        assert_eq!(resolved, vec!["app.conf", "app.prod.conf"]);
    }

    #[test]
    fn test_resolve_files_recursive_glob() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(store_dir.join("sub")).unwrap();

        std::fs::write(store_dir.join("top.conf"), "...").unwrap();
        std::fs::write(store_dir.join("sub").join("nested.conf"), "...").unwrap();
        std::fs::write(store_dir.join("sub").join("other.txt"), "...").unwrap();

        // `*.conf` matches at any depth (leaf name match).
        let resolved = resolve_files(&store_dir, &[], &["*.conf".into()], &[]);
        assert_eq!(resolved, vec!["sub/nested.conf", "top.conf"]);
    }

    #[test]
    fn test_resolve_files_recursive_scoped_pattern() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(store_dir.join("sub")).unwrap();

        std::fs::write(store_dir.join("top.conf"), "...").unwrap();
        std::fs::write(store_dir.join("sub").join("nested.conf"), "...").unwrap();

        // `sub/*.conf` scopes to the subdirectory.
        let resolved = resolve_files(&store_dir, &[], &["sub/*.conf".into()], &[]);
        assert_eq!(resolved, vec!["sub/nested.conf"]);
    }

    #[test]
    fn test_resolve_files_ignore_directory() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(store_dir.join("scratch")).unwrap();

        std::fs::write(store_dir.join("keep.conf"), "...").unwrap();
        std::fs::write(store_dir.join("scratch").join("junk.conf"), "...").unwrap();
        std::fs::create_dir_all(store_dir.join("scratch").join("deep")).unwrap();
        std::fs::write(
            store_dir.join("scratch").join("deep").join("also.conf"),
            "...",
        )
        .unwrap();

        // `scratch/` ignores the entire subdirectory tree.
        let resolved = resolve_files(&store_dir, &[], &["*.conf".into()], &["scratch/".into()]);
        assert_eq!(resolved, vec!["keep.conf"]);
    }

    #[test]
    fn test_resolve_files_ignore_recursive_wildcard() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(store_dir.join("sub")).unwrap();

        std::fs::write(store_dir.join("top.conf"), "...").unwrap();
        std::fs::write(store_dir.join("top.bak"), "...").unwrap();
        std::fs::write(store_dir.join("sub").join("nested.bak"), "...").unwrap();
        std::fs::write(store_dir.join("sub").join("nested.conf"), "...").unwrap();

        // `*.bak` matches at any depth.
        let resolved = resolve_files(
            &store_dir,
            &[],
            &["*.conf".into(), "*.bak".into()],
            &["*.bak".into()],
        );
        assert_eq!(resolved, vec!["sub/nested.conf", "top.conf"]);
    }

    #[test]
    fn test_resolve_files_empty_dirs_yield_no_matches() {
        let tmp = tempfile::tempdir().unwrap();
        let store_dir = tmp.path().join("mystore");
        std::fs::create_dir_all(store_dir.join("empty")).unwrap();
        std::fs::write(store_dir.join("real.conf"), "...").unwrap();

        // Empty directories produce no matches, no errors.
        let resolved = resolve_files(&store_dir, &[], &["*.conf".into()], &[]);
        assert_eq!(resolved, vec!["real.conf"]);
    }
}
